In [1]:
import tensorflow as tf
import numpy as np

In [3]:
cont1 = tf.constant(10)
tf_one = tf.ones([5,5])
tf_fill = tf.fill([4,3],2)
tf_zeros= tf.zeros([2,1])

In [5]:
print(cont1)

Tensor("Const_1:0", shape=(), dtype=int32)


In [7]:
ses = tf.Session()
ses.run(cont1)

10

In [8]:
ses.run(tf_zeros)

array([[0.],
       [0.]], dtype=float32)

In [34]:
initr = tf.global_variables_initializer()

Variables

In [24]:
A = tf.Variable(initial_value=np.random.normal(0,1,[5,5]))

In [18]:
B = tf.constant(np.ones((5,1)))

In [28]:
C = tf.matmul(A,B)

In [29]:
C

<tf.Tensor 'MatMul_1:0' shape=(5, 1) dtype=float64>

In [43]:
ses = tf.Session()
ses.run(initr)
ra,rb = ses.run([A,B])

In [46]:
rb

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [49]:
A = tf.placeholder(shape=[None,5],dtype=np.float32)

In [48]:
B = tf.placeholder(shape=[None,5],dtype=tf.float32)

In [53]:
ses.run(A+B,feed_dict={A:np.ones([5,5]),B:np.zeros([5,5])})

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

Example

In [85]:
n_feature = 1
n_neuron = 1


In [11]:
#Input
X = tf.placeholder(dtype=tf.float32,shape=(None,n_feature))
#Weight
W = tf.Variable(initial_value=tf.random_normal([n_feature,n_neuron]))
b = tf.Variable(initial_value= tf.zeros([n_neuron]))
initr = tf.global_variables_initializer()

In [12]:
Y = tf.matmul(X,W)+b

In [13]:
#Test
with tf.Session() as ses:
    ses.run(initr)
    res = ses.run(Y,feed_dict = {X : np.random.normal(size = [10,5])})

In [14]:
res

array([[-0.23846829],
       [-1.522579  ],
       [ 0.781018  ],
       [ 6.215847  ],
       [ 1.9116577 ],
       [-2.1343727 ],
       [ 1.1772492 ],
       [ 0.6946937 ],
       [-1.7913477 ],
       [-0.8304826 ]], dtype=float32)

In [86]:
X_train = np.random.normal(size = [10,1])

In [87]:
real_W = np.random.normal(size=[1,1])
real_b = np.ones([10,1])
Y_train = np.random.normal(X_train.dot(real_W))+real_b

In [88]:
#Fail for matrix W
W = tf.Variable(initial_value=tf.random_normal([n_feature,n_neuron]))
b = tf.Variable(initial_value= tf.zeros([n_neuron]))
initr = tf.global_variables_initializer()
optimizer = tf.train.GradientDescentOptimizer(learning_rate =0.01)
Cost = 0
for x,y in zip(X_train,Y_train):
    Y_pred = x*W+b
    Cost += (y-Y_pred)**2
    


In [89]:
train = optimizer.minimize(Cost)

In [99]:
with tf.Session() as ses:
    ses.run(initr)
    for i in range(1000):
        ses.run(train)
    tb,tw = ses.run([b,W])

In [100]:
tb,tw

(array([1.1407505], dtype=float32), array([[1.4776598]], dtype=float32))

In [101]:
real_W

array([[1.83733602]])

Example2

In [150]:
x_data = np.linspace(0,10,10000)
noise = np.random.normal(0,.11,len(x_data))

In [151]:
y_true = .5*x_data+1.0+noise

In [173]:
#batch
batch_size = 10
m=tf.Variable(0.5)
b = tf.Variable(1.0)
px =  tf.placeholder(tf.float32,[batch_size])
py =  tf.placeholder(tf.float32,[batch_size])
modely = m*px+b
error = tf.reduce_sum(tf.square(py-modely))

In [177]:
initr = tf.global_variables_initializer()
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.0001)
train = optimizer.minimize(error)

In [178]:
with tf.Session() as ses:
    ses.run(initr)
    #batch = int(len(x_data)/batch_size)
    batch = 10
    for i in range(batch):
        sample_ind = np.random.randint(len(x_data),size = batch_size)
        feed  = {px:x_data[sample_ind], py:y_true[sample_ind]}
        ses.run(train,feed_dict = feed)
        #print(ses.run([px,modely],feed_dict = feed))
    tm,tb = ses.run([m,b])

In [179]:
tm,tb

(0.4999889, 0.99997646)

In [158]:
sample_ind = np.random.randint(len(x_data),size = batch_size)

In [159]:
sample_ind

array([7981, 6135, 3142, 1165, 5825])

In [160]:
x_data[sample_ind]

array([7.98179818, 6.13561356, 3.14231423, 1.16511651, 5.82558256])

In [161]:
y_true[sample_ind]

array([5.09343792, 3.97919587, 2.26893924, 1.54754583, 3.76951532])

In [163]:
modely

<tf.Tensor 'add_260:0' shape=(5,) dtype=float32>